# lithiumcarbon Configuration
debug: false

hook:
  worldguard: true
  sertraline: true

file-load:
  loot: "^(?![#!]).*\\.(?i)(yaml|yml|toml|tml|json|conf)$"

database:
  enable: false  # true: MySQL; false: SQLite
  host: localhost
  port: 3306
  user: x_angelkawaii_x
  password: angelkawaii2
  database: lithiumcarbon
  table: lithiumcarbon_data

default-options:
  add-lore: null
  remove-lore: false

logger:
  ignore-errors:
    ErrorNoAvailableSlots: false
    ErrorNoPools: false
    ErrorItemGenerationFailed: false
    ErrorItemGenerationFailedNull: false
  ignore-warnings:
    WarningNotSupportDataComponent: false

allowed-blocks:
  - CHEST
  - GRAY_SHULKER_BOX

allowed-worlds:
  - *