# lithiumcarbon Configuration
debug: false

hook:
  worldguard: true
  sertraline: true

items:
  searching:
    material: YELLOW_STAINED_GLASS_PANE
    name: "<yellow>Searching..."
    lore: |
      Please wait ...
  waiting:
    material: GRAY_STAINED_GLASS_PANE
    name: "<red>???"
    lore: |
      Click to Search!

database:
  enable: false  # true: MySQL; false: SQLite
  host: localhost
  port: 3306
  user: x_angelkawaii_x
  password: angelkawaii2
  database: lithiumcarbon
  table: lithiumcarbon_data