# lithiumcarbon Configuration
debug: false

hook:
  worldguard: true
  # sertraline: true - Deprecated.

file-load:
  loots: "^(?![#!]).*\\.(?i)(yaml|yml|toml|tml|json|conf)$"

default-options:
  add-lore: null
  remove-lore: false

# Ignore warnings and errors
logger:
  ignore-errors:
    ErrorNoAvailableSlots: false
    ErrorNoPools: false
    ErrorItemGenerationFailed: false
    ErrorItemGenerationFailedNull: false
  ignore-warnings:
    WarningNotSupportDataComponent: false

# Allowed loot blocks
# Not support regex - if you want to support all blocks using allowed-all-blocks
allowed-blocks:
  - CHEST
  - GRAY_SHULKER_BOX

# Bypass allowed-blocks check
allowed-all-blocks: false

# Allowed loot worlds
# Supported regex
allowed-worlds:
  - "world.+"

# Bypass allowed-worlds check
allowed-all-worlds: true

default-layout:
  - '         '
  - '         '
  - '         '

sounds:
  open: "minecraft:block.chest.locked 1 0.6 block"
  search: "minecraft:item.armor.equip_chain 1 1 block"
  searching: "minecraft:block.stone_pressure_plate.click_on 1 0.5 block"
  search-end: "minecraft:block.dispenser.dispense 1 1 block"
  claim: "minecraft:block.stone_pressure_plate.click_on 1 1 block"